<?php
return [
	'taxonomy'    => 'taxonomy',
	'object_type' => '',
	'args'        => [
		'label'                 => 'taxonomy',
		'labels'                => [
			'name'              => __( '', 'player-key' ),
			'singular_name'     => __( '', 'player-key' ),
			'search_items'      => __( '', 'player-key' ),
			'all_items'         => __( '', 'player-key' ),
			'view_item '        => __( '', 'player-key' ),
			'parent_item'       => __( '', 'player-key' ),
			'parent_item_colon' => __( '', 'player-key' ),
			'edit_item'         => __( '', 'player-key' ),
			'update_item'       => __( '', 'player-key' ),
			'add_new_item'      => __( '', 'player-key' ),
			'new_item_name'     => __( '', 'player-key' ),
			'menu_name'         => __( '', 'player-key' ),
		],
		'description'           => '',
		'public'                => true,
		'publicly_queryable'    => false,
		'query_var'             => '',
		'show_in_nav_menus'     => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'show_tagcloud'         => true,
		'show_in_rest'          => true,
		'hierarchical'          => true,
		'update_count_callback' => '',
		'rewrite'               => true,
		'capabilities'          => [],
		'meta_box_cb'           => null,
		'show_admin_column'     => true,
		'show_in_quick_edit'    => true,
		'_builtin'              => false,
	],
];
