<?php
return [
	'post_type' => 'athlete',
	'args'      => [
		'label'               => __( 'Athlete', 'player-key' ),
		'labels'              => [
			'name'                  => __( 'Athletes', 'player-key' ),
			'singular_name'         => __( 'Athlete', 'player-key' ),
			'add_new'               => __( 'Add new Athlete', 'player-key' ),
			'add_new_item'          => __( 'Add new Athlete', 'player-key' ),
			'edit_item'             => __( 'Edit Athlete', 'player-key' ),
			'new_item'              => __( 'New Athlete', 'player-key' ),
			'view_item'             => __( 'View Athlete', 'player-key' ),
			'search_items'          => __( 'Search Athletes', 'player-key' ),
			'not_found'             => __( 'Not found', 'player-key' ),
			'not_found_in_trash'    => __( 'Not found in Trash', 'player-key' ),
			'parent_item_colon'     => __( 'Parent item colon', 'player-key' ),
			'menu_name'             => __( 'Athletes', 'player-key' ),
			'all_items'             => __( 'All Athletes', 'player-key' ),
			'archives'              => __( 'Archives', 'player-key' ),
			'insert_into_item'      => __( 'Insert into Athlete', 'player-key' ),
			'uploaded_to_this_item' => __( 'Uploaded to this Athlete', 'player-key' ),
			'featured_image'        => __( 'Featured Athlete image', 'player-key' ),
			'set_featured_image'    => __( 'Set featured image', 'player-key' ),
			'remove_featured_image' => __( 'Remove featured image', 'player-key' ),
			'use_featured_image'    => __( 'Use featured image', 'player-key' ),
			'filter_items_list'     => __( 'Filter Athletes list', 'player-key' ),
			'items_list_navigation' => __( 'Athletes list navigation', 'player-key' ),
			'items_list'            => __( 'Athletes list', 'player-key' ),
			'name_admin_bar'        => __( 'Athlete', 'player-key' ),
			'view_items'            => __( 'View Athletes', 'player-key' ),
			'attributes'            => __( 'Attributes', 'player-key' ),
		],
		'description'         => '',
		'public'              => true,
		'publicly_queryable'  => true,
		'exclude_from_search' => true,
		'show_ui'             => true,
		'show_in_menu'        => true,
		'show_in_admin_bar'   => true,
		'show_in_nav_menus'   => true,
		'show_in_rest'        => true,
		'menu_position'       => 80,
		'menu_icon'           => 'dashicons-superhero',
		'capability_type'     => 'page',
		'map_meta_cap'        => true,
		'hierarchical'        => false,
		'supports'            => [],
		'taxonomies'          => [],
		'has_archive'         => false,
		'query_var'           => true,
		'can_export'          => true,
	]
];
